@Restaurants.API_HostAddress = https://localhost:7207


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "Test Name",
  "description": "Test Description",
  "category": "Mexican",
  "hasDelivery": true,
  "city": "Metropolis",
  "street": "456 Gourmet Avenue",
  "postalCode": "54-321"
}

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
{
  "Name": "Teste patch",
  "Description": "Teste"


}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
  
}

###

@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

@dishId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/4

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/

###
