@Restaurants.API_HostAddress = https://localhost:7207
@token = JydkT2KHKBmCDnyFJ20u1Mx50VWCqdD8XMKfdhUhkhf2ZyWoiHKyReCFlZi0RjryiaqxmeuodvUFir49UVD96RhHaIXfmGi54eD6fR1NSpA1VVT0aNwf5YXw6t65V6DMyvc3BT4hc3roY


GET {{Restaurants.API_HostAddress}}/api/restaurants?pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###

@id=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "Test Name",
  "description": "Test Description",
  "category": "Mexican",
  "hasDelivery": true,
  "city": "Metropolis",
  "street": "456 Gourmet Avenue",
  "postalCode": "54-321"
}

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
{
  "Name": "Teste patch",
  "Description": "Teste"


}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
  
}

###

@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

@dishId=3
GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/4

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "testuser@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "testuser@test.com",
  "password": "Password1!"
}