@Restaurants.API_HostAddress = https://localhost:7207


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

@id=4
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "Test Name",
  "description": "Test Description",
  "category": "Mexican",
  "hasDelivery": true,
  "city": "Metropolis",
  "street": "456 Gourmet Avenue",
  "postalCode": "54-321"
}

###

@id=5
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

@id=6
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
{
  "Name": "Teste patch",
  "Description": "Teste"


}
###
